CREATE TABLE HanhKhach (
    MaHK VARCHAR(10) PRIMARY KEY,
    HoTen VARCHAR(50),
    CMND VARCHAR(12) UNIQUE,
    SDT VARCHAR(15),
    Email VARCHAR(50)
);

CREATE TABLE ChuyenBay (
    MaCB VARCHAR(10) PRIMARY KEY,
    SanBayDi VARCHAR(10),
    SanBayDen VARCHAR(10),
    GioKhoiHanh DATETIME,
    GioHaCanh DATETIME,
    GiaVe DECIMAL(10,2)
);

CREATE TABLE VeMayBay (
    MaVe VARCHAR(10) PRIMARY KEY,
    MaHK VARCHAR(10),
    MaCB VARCHAR(10),
    LoaiVe VARCHAR(20),
    TrangThai VARCHAR(20),
    NgayDat DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaHK) REFERENCES HanhKhach(MaHK),
    FOREIGN KEY (MaCB) REFERENCES ChuyenBay(MaCB)
);
